### ISSUE TITLE
error appears when dealing with Seurat object

### ISSUE THREAD

**Issue by wddyzxxx** [jamespeapen/Nvim-R#1]
Hello, I met Nvim-R today and I really found it convenient! So I sincerely hope to see it become better!
Ok, below is the output information appeared on my screen. All what I did was just produce a picture:

![image](https://user-images.githubusercontent.com/90907990/179749569-bd37357c-7861-4f64-a941-145067bb2630.png)
![image](https://user-images.githubusercontent.com/90907990/179749444-7f521f8b-fc14-4c33-aa45-2530d8e99cb8.png)

Also, it seems that anything concerned with SeuratObject, no matter what function I use, the error always comes.
![image](https://user-images.githubusercontent.com/90907990/179749824-532e7d6e-4812-4ee8-b4f1-ca61b72f342a.png)

Looking forward to your reply!

**Comment by jamespeapen** [comment]
Hi @wddyzxxx, it would be better if you opened this issue in the [parent repo](https://github.com/jalvesaq/Nvim-R/issues/new). This is just a fork for the online documentation. 
It would also be helpful when you make that issue if you added the `SessionInfo()` and context around the plotting code or a reproducible example if you can.

**Comment by wddyzxxx** [comment]
Hi&nbsp;jamespeapen, I noticed that you had made a markdown version of Nvim-R official documentation. And coincidently, yesterday when I saw the official version, which is not very convenient for users to find what they need, so I came up with an idea——how about making it into an online book using tools like gitbook?&nbsp; Especially because there have not existed a detailed tutorial of chinese version. So the moment I found your markdown version I wanted to know whether you would mind me translating your version based on your original&nbsp;typesetting style.&nbsp;
If not, then I will enthusiastically start my first contribution!
Looking forward to your reply!


&nbsp;
&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jamespeapen/Nvim-R"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月19日(星期二) 晚上9:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jamespeapen/Nvim-R] error appears when dealing with Seurat object (Issue #1)





 
Hi @wddyzxxx, it would be better if you opened this issue in the parent repo. This is just a fork for the online documentation.
 It would also be helpful when you make that issue if you added the SessionInfo() and context around the plotting code or a reproducible example if you can.

**Comment by jamespeapen** [comment]
The documentation belongs to @jalvesaq - I just ported it to the github wiki. You could open an issue on the parent repo to discuss translations.

**Comment by jalvesaq** [comment]
@wddyzxxx you should report the error at https://github.com/jalvesaq/Nvim-R/issues

Anyway, I can't replicate your example because you didn't show the code to create the objects `data.plot` and `ctrl`.

**Comment by wddyzxxx** [comment]
hhh, no wonder there isn't any issue. sry I did't notice that. And thank you for your valuable suggestions since&nbsp; I am still a rookie github user so far.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jamespeapen/Nvim-R"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月19日(星期二) 晚上9:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jamespeapen/Nvim-R] error appears when dealing with Seurat object (Issue #1)





 
Hi @wddyzxxx, it would be better if you opened this issue in the parent repo. This is just a fork for the online documentation.
 It would also be helpful when you make that issue if you added the SessionInfo() and context around the plotting code or a reproducible example if you can.
