### ISSUE TITLE
switch from R console to vim command mode

### ISSUE THREAD

**Issue by Cao-lab-zcmu** [jamespeapen/Nvim-R#2]
When all the vim edit interface closed, just the R console is open, how to switch from R console to vim command mode?
For example, I open a .R file, and then start R; I quit the file, now vim are in R console; there is a way restart a file without quit R console?

**Comment by jamespeapen** [comment]
Please open this issue in [the package repo](https://github.com/jalvesaq/Nvim-R/issues). This repo is only for the documentation.
