### ISSUE TITLE
keybinding for \aa not working (not mapped by default)

### ISSUE THREAD

**Issue by dmnkf** [jamespeapen/Nvim-R#3]
Hey I installed the plugin and almost everything works like a charm. Unfortunately, it seems like some keymappings which are documented are in fact not mapped. One example would be \aa or \su. 

Trying to map them myself in the config didn't work. What exactly would be the command to send the whole file? I assume it is RSendFile but I couldn't make it work. 

Thank you very much in advance.

**Comment by jamespeapen** [comment]
Please open this issue in [the package repo](https://github.com/jalvesaq/Nvim-R/issues). This repo is only for the documentation.

FWIW I can't replicate this issue - those bindings work for me. I would add a reproducible example when making this issue on the parent repo.
