### ISSUE TITLE
Missing/Inaccurate documentation in Wiki: Comment/Indent code

### ISSUE THREAD

**Issue by vladtarko** [jamespeapen/Nvim-R#4]
- [x] This is not an issue regarding the [Nvim-R](https://github.com/jalvesaq/Nvim-R) package functionality. Any bug reports or feature requests should be sent to the original repository: https://github.com/jalvesaq/Nvim-R/issues.

- [x] This is an issue regarding the documentation here in the wiki.
*Please indicate the relevant page(s).*
	- [ ]    Overview
	- [ ]    Main Features
	- [ ]    Installation
	- [ ]    Known Bugs and Workarounds
	- [ ]    Options
	- [ ]    Use
	- [x]    Custom Key Bindings
	- [ ]    License
	- [ ]    FAQ and Tips
	- [ ]    News

**Describe the issue**

Line: https://github.com/jamespeapen/Nvim-R/blob/0f204f3d98f109bb32701ed7759a134c5f4e28da/doc/Nvim-R.txt#L2673

I'm trying to use the following from the "Edit R code" section, without success:

    RSimpleComment
    RSimpleUnComment
    RToggleComment
    RIndent

In normal mode I tried:

    : call RToggleComment()

It says `E117: Unknown function RToggleComment`. Same issue with the others.

Am I using this wrong? Thanks!

(Ultimately I want to define a custom keymap for the toggle function.)

**Comment by jamespeapen** [comment]
I think those are available only if you define a mapping using those. If you look at the [example](https://github.com/jamespeapen/Nvim-R/wiki/Custom-Key-Bindings), it uses RStart, but `call RStart()` gives `E117: Unknown function RToggleComment`. When you put that function in your config, then the mapping works. I don't think that functions in that list are to be called directly.
