### ISSUE TITLE
Missing/Inaccurate documentation in Wiki

### ISSUE THREAD

**Issue by py9mrg** [jamespeapen/Nvim-R#5]
*Please check these boxes*

- [x] This is not an issue regarding the [Nvim-R](https://github.com/jalvesaq/Nvim-R) package functionality. Any bug reports or feature requests should be sent to the original repository: https://github.com/jalvesaq/Nvim-R/issues.

- [x] This is an issue regarding the documentation here in the wiki.
*Please indicate the relevant page(s).*
	- [x]    Overview
	- [ ]    Main Features
	- [ ]    Installation
	- [ ]    Known Bugs and Workarounds
	- [x]    Options
	- [ ]    Use
	- [ ]    Custom Key Bindings
	- [ ]    License
	- [ ]    FAQ and Tips
	- [ ]    News

Hello,

I just wanted to mention that it might be helpful to update some of the documentation that mentions options that can be used. Neovim has moved from vimrc to init.vim, to init.lua so the syntax can be quite different to what is listed here.

For example, to change `R_path` is now:

    vim.g.R_path = "path"

in `init.lua`, rather than:

    let R_path = "path"

in `vimrc`.

Perhaps you don't need to update all the documentation but maybe it is a good idea to write a mention of this (and how to translate vimrc -> init.lua) somewhere obvious. Many new Neovim users won't have ever had to know about vimrc (or init.vim), and that number will only grow.

*Please provide a link to the lines of the [original documentation](https://github.com/jamespeapen/Nvim-R/blob/master/doc/Nvim-R.txt) that you are using as a reference. You can click on the line number to get a link.*

**Comment by jamespeapen** [comment]
A neovim specific plugin has been created at https://github.com/R-nvim/R.nvim. Since this is about changes to the documentation rather than an error, feel free to open this on the parent repo.
