### ISSUE TITLE
terminal width is not updated (leading to truncation of output)

### ISSUE THREAD

**Issue by idavydov** [jamespeapen/Nvim-R#7]
Hi,

Thanks for the great package.

I have line numbers enabled in the buffer. When the number of rows is increasing beyond 100, the terminal width changes. But nvim-R doesn't seem to update `options(width = ...)`. Do you think this is something which can be fixed on the side of Nvim-R?

Here's how to reproduce the issue:

- Open R file
- Start R `\rf`
- Run the following code
```r
paste(rep("\n", 100)) |> cat()
rep(letters, 3) |> paste(collapse = "")
```

One of the alphabet letter is invisible.

![2023-09-29_16-48-58 (1)](https://github.com/jamespeapen/Nvim-R/assets/671660/7d933516-daa6-458c-beb9-897c7fcd3cdd)

**Comment by idavydov** [comment]
sorry, probably a wrong repository

**Comment by jamespeapen** [comment]
This repo is only for the wiki. You can open this in the parent repo. However, I'm not able to replicate this issue.
