### ISSUE TITLE
Missing/Inaccurate documentation in Wiki

### ISSUE THREAD

**Issue by raffaelemancuso** [jamespeapen/Nvim-R#9]
*Please check these boxes*

- [X] This is not an issue regarding the [Nvim-R](https://github.com/jalvesaq/Nvim-R) package functionality. Any bug reports or feature requests should be sent to the original repository: https://github.com/jalvesaq/Nvim-R/issues.

- [X] This is an issue regarding the documentation here in the wiki.
*Please indicate the relevant page(s).*
	- [ ]    Overview
	- [ ]    Main Features
	- [X]    Installation
	- [ ]    Known Bugs and Workarounds
	- [ ]    Options
	- [ ]    Use
	- [ ]    Custom Key Bindings
	- [ ]    License
	- [ ]    FAQ and Tips
	- [ ]    News

**Describe the issue**

[Here](https://github.com/jamespeapen/Nvim-R/wiki/Installation#troubleshooting), this:

> If the plugin is active, pressing rf should start R.

Should be:

> If the plugin is active, pressing `<LocalLeader>rf` should start R.

Especially since it is the first thing that users try to start it.

*Please provide a link to the lines of the [original documentation](https://github.com/jamespeapen/Nvim-R/blob/master/doc/Nvim-R.txt) that you are using as a reference. You can click on the line number to get a link.*

https://github.com/jamespeapen/Nvim-R/blob/9b466bd4b9b1a1fff3aefd86a28bb78b1e12518d/doc/Nvim-R.txt#L198

**Comment by jamespeapen** [comment]
Fixed - thanks!
